version: '3.4'

services:
   children-social-care-cpd:
      build:
         context: ./children-social-care-cpd

      environment:
        - CPD_AZURE_ENVIRONMENT=dev
        - CPD_CLARITY=g8ya7xv8ha
        - CPD_CONTENTFUL_ENVIRONMENT=dev
        - CPD_DELIVERY_KEY=MdMA0nFp21Iu3yY51kPiAYuR3vaU1vm6kDbRnrnDJqk
        - CPD_GOOGLEANALYTICSTAG=G-5HLRT2H3SW
        - CPD_PREVIEW_KEY=LlKKLs9L_XP02P4VFaAHRagsZeZwE5288Gcc_SNoZHM
        - CPD_SPACE_ID=ltt4ovp0xx0f
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_ENVIRONMENT=regression
      ports:
         - 5001:80
      networks:
         - cpd-network
   e2e:
      build:
        context: ../
      command: "yarn mocha-report"
      working_dir: /app
      
   