version: '3.4'

services:
   children-social-care-cpd:
      build:
         context: ../../Childrens-Social-Care-CPD

      environment:
        - CPD_AZURE_ENVIRONMENT=dev
        - CPD_CLARITY=g8ya7xv8ha
        - CPD_CONTENTFUL_ENVIRONMENT=dev
        - CPD_DELIVERY_KEY=MdMA0nFp21Iu3yY51kPiAYuR3vaU1vm6kDbRnrnDJqk
        - CPD_GOOGLEANALYTICSTAG=G-5HLRT2H3SW
        - CPD_PREVIEW_KEY=LlKKLs9L_XP02P4VFaAHRagsZeZwE5288Gcc_SNoZHM
        - CPD_SPACE_ID=ltt4ovp0xx0f
        - ASPNETCORE_URLS=http://+:81
        - ASPNETCORE_ENVIRONMENT=dev
      ports:
         - "81:8080"
      networks:
         - cpd-network
   e2e:
      build:
        context: ../
      command: "yarn mocha-report"
      working_dir: /app
      networks: 
        - cpd-network
      
networks:
   cpd-network:
      name: cpd-network
      
   