version: '3.4'

services:
  webapp:
    build:
      context: ./Childrens-Social-Care-CPD
    environment:
      - ASPNETCORE_URLS=http://+:80
      - CPD_GOOGLEANALYTICSTAG=$CPD_GOOGLEANALYTICSTAG
      - CPD_CONTENTFUL_ENVIRONMENT=$CPD_CONTENTFUL_ENVIRONMENT
      - CPD_SPACE_ID=$CPD_SPACE_ID
      - CPD_DELIVERY_KEY=$CPD_DELIVERY_KEY
      - CPD_PREVIEW_KEY=$CPD_PREVIEW_KEY
      - CPD_AZURE_ENVIRONMENT=$CPD_AZURE_ENVIRONMENT
      - CPD_INSTRUMENTATION_CONNECTIONSTRING=$CPD_INSTRUMENTATION_CONNECTIONSTRING
      - CPD_FEATURE_POLLING_INTERVAL=$CPD_FEATURE_POLLING_INTERVAL
    ports:
      - 5001:80