version: '3.4'

services:
  webapp:
    build:
      context: ./Childrens-Social-Care-CPD
    environment:
      - ASPNETCORE_URLS=http://+:80
      - CPD_GOOGLEANALYTICSTAG=$CPD_GOOGLEANALYTICSTAG
      - CPD_CONTENTFUL_ENVIRONMENT=$CPD_CONTENTFUL_ENVIRONMENT
      - CPD_SERVICE_ENVIRONMENT=$CPD_SERVICE_ENVIRONMENT
      - CPD_DELIVERY_API_KEY=$CPD_DELIVERY_API_KEY
      - CPD_PREVIEW_API_KEY=$CPD_PREVIEW_API_KEY
    ports:
      - 5001:80