{
 "title": "Azure Costs - Social Workforce - Production Resources",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Azure Costs for Production Environment - Main Application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "s185p01-childrens-social-care-cpd-rg"
    }
   ]
  },
  {
   "title": "Azure Costs for Production Environment - Main Application",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "s185p01-childrens-social-care-cpd-rg"
    }
   ]
  },
  {
   "title": "Azure Costs for Production Environment - Shared services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "s185p01-childrens-social-care-shared-rg"
    }
   ]
  },
  {
   "title": "Azure Costs for Production Environment - Shared services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "s185p01-childrens-social-care-shared-rg"
    }
   ]
  },
  {
   "title": "Azure Costs for Production Environment - Terraform State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    { "constant": 6.5, "queryText": "s185p01-tfstate-rg" }
   ]
  },
  {
   "title": "Azure Costs for Production Environment - Terraform State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "constant": 6.5, "queryText": "s185p01-tfstate-rg" }
   ]
  },
  {
   "title": "Azure Costs for Production Environment - DfE Core Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    { "constant": 6.5, "queryText": "s185p01-core" }
   ]
  },
  {
   "title": "Azure Costs for Production Environment - DfE Core Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "constant": 6.5, "queryText": "s185p01-core" }
   ]
  }
 ]
}