{
 "title": "Production Environment - Azure Metrics - s185p01",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Production App Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WAF protection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AzwafBotProtection",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-csc-cpd-app-gateway",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AzwafSecRule",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-csc-cpd-app-gateway",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AverageMemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "CPU Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuTime",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Count Http status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http2xx",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http401",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http403",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http404",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http406",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Http 404 Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http404",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Count of Http Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http5xx",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AverageMemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Data In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Data Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-chidrens-social-care-cpd-app-service",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  { "title": "Production App Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Healthy and Unhealthy Host Count for s18pt01 App Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-csc-cpd-app-gateway",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UnhealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-csc-cpd-app-gateway",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Total Requests for s185p01 App Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-csc-cpd-app-gateway",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Failed Requests for s185p01 App Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FailedRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-csc-cpd-app-gateway",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Backend Connect Time for s185p01 App Gateway",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BackendConnectTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-csc-cpd-app-gateway",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Response Status for s185p01 App Gateway",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ResponseStatus",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-csc-cpd-app-gateway",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Last byte backend response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BackendLastByteResponseTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
        "resourceName": "s185p01-csc-cpd-app-gateway",
        "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
    }
   ]
  },
  {
   "title": "Production Search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Search Queries Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "SearchQueriesPerSecond",
        "metricNamespace": "microsoft.search/searchservices",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Search/searchServices",
          "region": "westeurope",
          "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
          "resourceName": "s185p01-ai-search-service",
          "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
      }
     ]
    },
    {
     "title": "Total Search Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "SearchLatency",
        "metricNamespace": "microsoft.search/searchservices",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Search/searchServices",
          "region": "westeurope",
          "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
          "resourceName": "s185p01-ai-search-service",
          "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
      }
     ]
    },
    {
     "title": "Throttled Search Queries (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "ThrottledSearchQueriesPercentage",
        "metricNamespace": "microsoft.search/searchservices",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Search/searchServices",
          "region": "westeurope",
          "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
          "resourceName": "s185p01-ai-search-service",
          "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
      }
     ]
    },
    {
     "title": "Total Documents Processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "DocumentsProcessedCount",
        "metricNamespace": "microsoft.search/searchservices",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Search/searchServices",
          "region": "westeurope",
          "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
          "resourceName": "s185p01-ai-search-service",
          "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
      }
     ]
    },
    {
     "title": "Total Skill execution invocation Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "SkillExecutionCount",
        "metricNamespace": "microsoft.search/searchservices",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Search/searchServices",
          "region": "westeurope",
          "resourceGroup": "s185p01-childrens-social-care-cpd-rg",
          "resourceName": "s185p01-ai-search-service",
          "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "405fef5a-3984-4bb2-9e3e-f09369b21755"
      }
     ]
    }
   ]
  }
 ]
}