{
 "title": "Azure Costs - Social Workforce - Development",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Azure Costs for s185-social workforce-development",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    { "constant": 6.5 }
   ]
  },
  {
   "title": "Azure Costs for s185-social workforce-development",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "constant": 6.5 }
   ]
  },
  {
   "title": "Azure Costs for s185d01-childrens-social-care-cpd-rg by Date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "s185d01-childrens-social-care-cpd-rg"
    }
   ]
  },
  {
   "title": "Azure Costs for s185d01-childrens-social-care-cpd-rg",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "s185d01-childrens-social-care-cpd-rg"
    }
   ]
  },
  {
   "title": "Azure Costs for s185d01-childrens-social-care-shared-rg by Date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "s185d01-childrens-social-care-shared-rg"
    }
   ]
  },
  {
   "title": "Azure Costs for s185d01-childrens-social-care-shared-rg",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "s185d01-childrens-social-care-shared-rg"
    }
   ]
  },
  {
   "title": "Azure Costs for s185d01-tfstate-rg by Date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    { "constant": 6.5, "queryText": "s185d01-tfstate-rg" }
   ]
  },
  {
   "title": "Azure Costs for s185d01-tfstate-rg",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "constant": 6.5, "queryText": "s185d01-tfstate-rg" }
   ]
  },
  {
   "title": "Azure Costs fors185d01-core by Date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    { "constant": 6.5, "queryText": "s185d01-core" }
   ]
  },
  {
   "title": "Azure Costs for s185d01-core",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "constant": 6.5, "queryText": "s185d01-core" }
   ]
  }
 ]
}