{
 "title": "Azure Metrics - Development-02",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "CPU Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuTime",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AverageMemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    }
   ]
  },
  {
   "title": "Count of Http status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http2xx",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http401",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http403",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http404",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http406",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    }
   ]
  },
  {
   "title": "Http 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http2xx",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    }
   ]
  },
  {
   "title": "Count of Http Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http5xx",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    }
   ]
  },
  {
   "title": "Http 404 Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http404",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    }
   ]
  },
  {
   "title": "Data In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    }
   ]
  },
  {
   "title": "Data Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/sites",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "westeurope",
        "resourceGroup": "s185d02-childrens-social-care-cpd-rg",
        "resourceName": "s185d02-chidrens-social-care-cpd-app-service",
        "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
    }
   ]
  }
 ]
}