{
 "title": "Azure Metrics -LoadTest-s185d03",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "s185d03 App Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Consumption",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "CpuTime",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "AverageMemoryWorkingSet",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Count Http status codes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http2xx",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      },
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http401",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      },
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http403",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      },
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http404",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      },
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http406",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Count of Http Server Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http5xx",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Http 2xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http2xx",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Http 404 Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http404",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Requests",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         300000,
         3600000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "HttpResponseTime",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "microsoft.web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Data In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "BytesReceived",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Data Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "BytesSent",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-chidrens-social-care-cpd-app-service",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    }
   ]
  },
  {
   "title": "s185d03 App Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Healthy and Unhealthy Host Count for s185d03 App Gateway",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "HealthyHostCount",
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "West Europe",
        "resources": [
         {
          "metricNamespace": "Microsoft.Network/applicationGateways",
          "region": "West Europe",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-csc-cpd-app-gateway",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      },
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "UnhealthyHostCount",
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "West Europe",
        "resources": [
         {
          "metricNamespace": "Microsoft.Network/applicationGateways",
          "region": "West Europe",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-csc-cpd-app-gateway",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Total Requests for s185d03 App Gateway",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 2 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "TotalRequests",
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "West Europe",
        "resources": [
         {
          "metricNamespace": "Microsoft.Network/applicationGateways",
          "region": "West Europe",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-csc-cpd-app-gateway",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Failed Requests for s185d03 App Gateway",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "FailedRequests",
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "West Europe",
        "resources": [
         {
          "metricNamespace": "Microsoft.Network/applicationGateways",
          "region": "West Europe",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-csc-cpd-app-gateway",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Backend Connect Time for s185d03 App Gateway",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "BackendConnectTime",
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "West Europe",
        "resources": [
         {
          "metricNamespace": "Microsoft.Network/applicationGateways",
          "region": "West Europe",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-csc-cpd-app-gateway",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Response Status for s185d03 App Gateway",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "ResponseStatus",
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "West Europe",
        "resources": [
         {
          "metricNamespace": "Microsoft.Network/applicationGateways",
          "region": "West Europe",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-csc-cpd-app-gateway",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    }
   ]
  },
  {
   "title": "s185d03 Search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Memory working set",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "AverageMemoryWorkingSet",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Count Http status codes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http2xx",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      },
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http401",
        "metricNamespace": "microsoft.web/sites",
        "region": "West Europe",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "West Europe",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      },
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http403",
        "metricNamespace": "microsoft.web/sites",
        "region": "West Europe",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "West Europe",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      },
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http404",
        "metricNamespace": "microsoft.web/sites",
        "region": "West Europe",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "West Europe",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Count Of Http Server Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http5xx",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Http 2xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http2xx",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Http 2xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Http2xx",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Count Of Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Requests",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "HttpResponseTime",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Data In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "BytesReceived",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    },
    {
     "title": "Data Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "BytesSent",
        "metricNamespace": "microsoft.web/sites",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.Web/sites",
          "region": "westeurope",
          "resourceGroup": "s185d03-childrens-social-care-cpd-rg",
          "resourceName": "s185d03-search",
          "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "31a2beaa-81c6-47f4-8b88-02f0419dc2a3"
      }
     ]
    }
   ]
  }
 ]
}