version: '3.4'

services:
   children-social-care-cpd:
      build:
         context: ../Childrens-Social-Care-CPD
      environment:
        - CPD_AZURE_ENVIRONMENT=dev
        - CPD_CLARITY=${CPD_CLARITY}
        - CPD_CONTENTFUL_ENVIRONMENT=dev
        - CPD_DELIVERY_KEY=${CPD_DELIVERY_KEY}
        - CPD_GOOGLEANALYTICSTAG=${CPD_GOOGLEANALYTICSTAG}
        - CPD_PREVIEW_KEY=${CPD_PREVIEW_KEY}
        - CPD_SPACE_ID=${CPD_SPACE_ID}
        - ASPNETCORE_URLS=http://+:81
        - ASPNETCORE_ENVIRONMENT=dev
      ports:
         - 8080:81
   children-social-care-cpd-regression-suite:
      build:
        context: ./
      command: "yarn mocha-report"
      working_dir: /app