name: App Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to deploy (use @ or :)'
        required: true
        default: ':master'
      workspace:
        description: 'Environment to deploy to on Azure'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Dev
          - Test
          - Pre-Prod
          - Prod
          - Load-Test

jobs:
  app-deploy:
    name: 'App Deploy'
    runs-on: ubuntu-latest
    environment: ${{inputs.workspace}}

    steps:

      - name: Sign in to Azure 
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.TF_ARM_CLIENT_ID }}","clientSecret":"${{ secrets.TF_ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.TF_ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TF_ARM_TENANT_ID }}"}'

      - name: Deploy Dev to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 's185d01-chidrens-social-care-cpd-app-service'
          # slot-name: 'Dev'
          images: 'ghcr.io/dfe-digital/childrens-social-care-cpd${{ inputs.tag }}'
        if: ${{ inputs.workspace == 'Dev' }}

      - name: Deploy Test to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 's185d02-chidrens-social-care-cpd-app-service'
          # slot-name: 'Test'
          images: 'ghcr.io/dfe-digital/childrens-social-care-cpd${{ inputs.tag }}'
        if: ${{ inputs.workspace == 'Test' }}

      - name: Deploy Load-Test to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 's185d03-chidrens-social-care-cpd-app-service'
          slot-name: 'staging'
          images: 'ghcr.io/dfe-digital/childrens-social-care-cpd${{ inputs.tag }}'
        if: ${{ inputs.workspace == 'Load-Test' }}

      - name: Deploy Pre-Prod to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 's185t01-chidrens-social-care-cpd-app-service'
          # slot-name: 'Pre-Prod'
          images: 'ghcr.io/dfe-digital/childrens-social-care-cpd${{ inputs.tag }}'
        if: ${{ inputs.workspace == 'Pre-Prod' }}

      - name: Deploy Prod to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 's185p01-chidrens-social-care-cpd-app-service'
          slot-name: 'staging'
          images: 'ghcr.io/dfe-digital/childrens-social-care-cpd${{ inputs.tag }}'
        if: ${{ inputs.workspace == 'Prod' }}

      - name: Sign out of Azure
        run: |
          az logout
  
