name: Contentful Schema Migrate

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    env:
      DELIVERY_KEY: ${{ secrets.TF_VAR_CPD_DELIVERY_KEY }}
      SPACE_ID: ${{ secrets.TF_VAR_CPD_SPACE_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm packages used by util scripts
        working-directory: ./Utilities
        run: npm ci

      - name: Generate sitemap
        id: generate-sitemap
        working-directory: ./Utilities
        run: node generate-sitemap.js