name: Locust oad testing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: apardo04/locust-github-action@master
        with:
          LOCUSTFILE: "./LoadTest/locustfile.py"
          URL:  "https://dev.develop-child-family-social-work-career.education.gov.uk"
          USERS: "1"
          RATE: "1"
          RUNTIME: "60s"