name: MB Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev

    env:
      FILE_PATH: Utilities/temp.txt

    steps:
      - uses: actions/checkout@v4

      - name: Git Status 1
        run: git status

      - name: Conditional 1
        id: conditional1
        run: if git status | grep -q "${{ env.FILE_PATH }}"; then exit 1; fi

      - name: Test 1
        run: echo ${{ steps.conditional1.outcome }}

      - name: Conditional execution 1
        if: ${{ steps.conditional1.outcome }} == "failure"
        run: echo "ONLY DO THIS IF CONDITIONAL1 FAILED"

      - name: Update textfile
        working-directory: ./Utilities
        run: date > temp.txt

      - name: Git Status 2
        run: git status
        
      - name: Conditional 2
        id: conditional2
        continue-on-error: true
        run: if git status | grep -q "${{ env.FILE_PATH }}"; then exit 1; fi

      - name: Test 2a
        run: echo "Outcome- ${{ steps.conditional2.outcome }}"

      - name: Test 2b
        run: echo "Conclusion- ${{ steps.conditional2.conclusion }}"

      - name: Conditional execution 2
        if: ${{ steps.conditional2.outcome }} == "failure"
        run: echo "ONLY DO THIS IF CONDITIONAL2 FAILED"

      - name: Final step
        run: echo "ALWAYS DO THIS"