name: Restore Contentful

on:
  workflow_dispatch:

jobs:
  restore:
    name: 'Restore Contentful'
    runs-on: ubuntu-latest
    environment: Prod
    env:
      ENVID: prod
      SPACE: ${{ secrets.TF_VAR_CPD_SPACE_ID }}
      MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}

    steps:
    - name: Checkout destination repository
      uses: actions/checkout@v2
      with:
        repository: DFE-Digital/childrens-social-care-cpd-contentful-backup
        token: ${{ secrets.BACKUP_REPO_PAT }}
        path: restore

    - name: Restore Content
      run: docker run --rm -e token=$MANAGEMENT_TOKEN -e space=$SPACE -e envid=$ENVID -v $PWD/restore:/opt/backup ghcr.io/dfe-digital/contentful-space-import:master
