name: Restore Contentful

on:
  workflow_dispatch:

jobs:
  restore:
    name: 'Restore Contentful'
    runs-on: ubuntu-latest
    env:
      ENVID: dev
      SPACE: ${{ secrets.TF_VAR_CPD_SPACE_ID }}
      MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}

    steps:
    - name: Checkout destination repository
      uses: actions/checkout@v2
      with:
        repository: DFE-Digital/childrens-social-care-cpd-contentful-backup
        token: ${{ secrets.BACKUP_REPO_PAT }}
        path: restore

    - name: Restore Content
      run: docker run --rm -v $PWD/restore:/opt/restore ghcr.io/dfe-digital/contentful-space-export:master /bin/sh -c "contentful space import --management-token $MANAGEMENT_TOKEN --space-id $SPACE --environment-id $ENV_ID --content-file /opt/backup/prod-contentful-backup-output.json"
