name: Static code analysis

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  code-analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu" # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud coverage
        id: cache-sonar-coverage
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-coverage
          restore-keys: ${{ runner.os }}-coverage

      - name: Install SonarCloud scanners
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install SonarCloud coverage
        if: steps.cache-sonar-coverage.outputs.cache-hit != 'true'
        run: dotnet tool install --global dotnet-coverage

      - name: Build, Test and Analyze
        env:
          SONAR_TOKEN_AS: ${{ secrets.SONAR_TOKEN_AS }}
        run: |
          dotnet-sonarscanner begin \
            /k:"as2024ad_sfsw" \
            /o:"as2024ad" \            
            /d:sonar.qualitygate.wait=true \
            /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml \
            /d:sonar.exclusions="**/*.css,**/*.scss,**/Models/*,**/Program.cs,**/WebApplicationBuilderExtensions.cs,**/GraphQL/Queries/*,**/Contentful-Schema/migrations/*.cjs" \
            /d:sonar.test.exclusions="Childrens-Social-Care-CPD-Tests/**/*,Terraform-bootstrap/Error-pages/*" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN_AS }}" \
            /d:sonar.project-key="${{ secrets.SONAR_PROJECT_KEY_AS }}" \
            /d:sonar.host.url="https://sonarcloud.io"
          dotnet build --no-incremental
          dotnet-coverage collect --settings dotnet-cover-config.xml -f xml -o coverage.xml "dotnet test"
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN_AS }}"
