name: 'Terraform Destroy'

on: 
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Terraform Workspace which should map to GitHub Environment'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Dev
          - Test
          - Pre-Prod
          - Prod

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: ${{inputs.workspace}}
    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
      TF_VAR_tenant_id: ${{secrets.TF_ARM_TENANT_ID}}
      TF_VAR_cpd_client_id: ${{secrets.TF_VAR_CPD_CLIENT_ID}}
      TF_VAR_cpd_client_secret: ${{secrets.TF_VAR_CPD_CLIENT_SECRET}}
      TF_VAR_cpd_keyvaultendpoint: ${{secrets.TF_VAR_CPD_KEYVAULTENDPOINT}}
      TF_VAR_acr_password: ${{secrets.TF_VAR_ACR_PASSWORD}}
      TF_WORKSPACE: ${{inputs.workspace}}

    defaults:
      run:
        shell: bash

    steps:
  
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir=Terraform init

    - name: Terraform Destroy
      run: terraform -chdir=Terraform destroy -auto-approve -input=false
