name: Trivy Vulnerability Scan

on:
  push:
    branches: [next, main]
  pull_request:
    branches: [next, main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Trivy File Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4     

      - name: Run Trivy file scan
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
        with:
          scan-type: 'fs'
          scan-ref: '.'          
          ignore-unfixed: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: 0
          vuln-type: os,library
          scanners: vuln,secret,misconfig,license

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
